### ISSUE TITLE
lambda lifting contains a few possible typo

### ISSUE THREAD

**Issue by KisaragiEffective** [haskellfoundation/hs-opt-handbook.github.io#85]
Hi,

I've found that https://github.com/haskellfoundation/hs-opt-handbook.github.io/blob/main/src/Optimizations/GHC_opt/lambda_lifting.rst contains some possible typo. The corresponding source is https://github.com/haskellfoundation/hs-opt-handbook.github.io/blob/0fefd8f50fddfc7cdd14f44d8d6b07fbb791bc81/src/Optimizations/GHC_opt/lambda_lifting.rst?plain=1#L40 and https://github.com/haskellfoundation/hs-opt-handbook.github.io/blob/0fefd8f50fddfc7cdd14f44d8d6b07fbb791bc81/src/Optimizations/GHC_opt/lambda_lifting.rst?plain=1#L47.

Would you assign me to this ticket (if this is actually not as intended)? Thank you!

**Comment by doyougnu** [comment]
Aha! Thanks for the proof read. That chapter (like all the chapters) is still in draft phase so I am not surprised that these typos exist. I'd be happy to merge a PR for this and add you to the contributors list if you want to make the change.

**Comment by doyougnu** [comment]
Also apologies for the delay in responding. I was taking a writing break after the FUNARCH deadline on June 1st :)
