### ISSUE TITLE
Fork Kilister for a case study

### ISSUE THREAD

**Issue by theGhostJW** [haskellfoundation/hs-opt-handbook.github.io#93]
It would be really useful to have a link to a forked repo at the start of the case study with each step in the optimisation process tagged.
This would enable working through the steps described as a tutorial.
https://haskell.foundation/hs-opt-handbook.github.io/src/Case_Studies/klister.html

**Comment by doyougnu** [comment]
Hi! Thanks for the issue. 

This is a good idea but I worry about a maintenance burden. What is the benefit of a fork over just linking to the proper commit? For example, for klister this would be: https://github.com/gelisam/klister/commit/5aea4d2b9df8f6e9db276078570c1e1bd1306cd3
Which is the commit before the PR that inspired the case study.

**Comment by theGhostJW** [comment]
Probably none. A link to the commit would be fine.
